#!/usr/bin/env bash
# gets domain info
# shellcheck disable=SC2086
if [ $# -eq 1 ]; then
    host -a "www.$1" | awk '{if(/^www./) print "The subdomain www is a", $4, "record and points to", $5}'
    host -a "lb-01.$1" | awk '{if(/^lb-01./) print "The subdomain lb-01 is a", $4, "record and points to", $5}'
    host -a "web-01.$1" | awk '{if(/^web-01./) print "The subdomain web-01 is a", $4, "record and points to", $5}'
    host -a "web-02.$1" | awk '{if(/^web-02./) print "The subdomain web-02 is a", $4, "record and points to", $5}'
elif [ $# -eq 2 ]; then
    host -a $2.$1 | awk -v subdo="$2" '{if(/^subdo./) print "The subdomain www is a", $4, "record and points to", $5}'
fi
