#!/usr/bin/env bash
# sets up new serv with 404 config
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "11iadd_header X-Served-By \"$HOSTNAME\";\n" /etc/nginx/nginx.conf
sudo service nginx restart
