#!/usr/bin/env bash
# shellcheck disable=SC2154
# sets up load balancer
sudo apt-get -y update
# Thanks Sue!!!
# https://haproxy.debian.net/#?distribution=Ubuntu&release=trusty&version=1.8
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get install -y haproxy=1.8.\*

sudo sed -i "s/ENABLED=0/ENABLED=1/g" /etc/default/haproxy


echo "listen 250-lb-01
        bind 0:80
        mode http
        stats enable
        balance roundrobin
        option httpclose
        option forwardfor
        server 250-web-01 34.227.229.159 check port 80
        server 250-web-02 34.229.125.244 check port 80" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
