#!/usr/bin/env bash
#new nginx server with default index
sudo apt-get -y install nginx
new_str='54.242.127.159;\n'
pttrn='localhost;/s/localhost;'
sed -i '0,/$pattrn/$new_str/' /etc/nginx/sites-available/default
echo "Holberton School" > /usr/share/nginx/html/index.html
sudo service nginx restart
