#!/usr/bin/env bash
#new serv with a redirect config
sudo apt-get -y install nginx
new_str='54.242.127.159;\n\tlocation = \/redirect_me {\n\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4\n\t}\n'
pttrn='localhost;/s/localhost;'
sed -i '0,/$pattrn/$new_str/' /etc/nginx/sites-available/default
sudo service nginx restart
