#!/usr/bin/env bash
# sets up new serv with 404 config
sudo apt-get -y install nginx
new_str='54.242.127.159;\n'
pttrn='localhost;/s/localhost;'
sed -i '0,/$pattrn/$new_str/' /etc/nginx/sites-available/default
sed -i "s/#error_page 401/error_page 401/" /etc/nginx/sites-available/default
touch /usr/share/nginx/html/404.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
sudo service nginx restart
